FROM oven/bun:latest

WORKDIR /app/apps/worker

COPY ./apps/worker/ ./apps/worker

# Copy package.json first
COPY ./packages/ ./packages
COPY package.json .

# Install dependencies
RUN bun install
RUN pnpm run db:generate

EXPOSE 4000

CMD ["pnpm", "run", "worker"]