FROM node:iron-bullseye

WORKDIR /app

# Install Bun
RUN npm install -g bun

COPY ./apps/primary-backend/ ./apps/primary-backend
COPY ./packages/ ./packages
COPY package.json .
COPY bun.lock .

RUN bun install
RUN bun run db:generate

EXPOSE 3000

CMD ["bun", "run", "primary-backend"]
