FROM node:iron-bullseye

WORKDIR /app

RUN npm install -g bun

COPY ./apps/k8s-orchastrator/ ./apps/k8s-orchastrator

# Copy package.json first
COPY ./packages/ ./packages
COPY package.json .
COPY bun.lock ./

# Install dependencies
RUN bun install
RUN bun run db:generate

EXPOSE 9000

CMD ["bun", "run", "k8s-orchastrator"]