FROM node:23-alpine
RUN npm install -g pnpm
RUN npm install -g bun

WORKDIR /app/

COPY ./apps/worker/ ./apps/worker

# Copy package.json first
COPY ./packages/ ./packages
COPY package.json .
COPY pnpm-workspace.yaml .

# Install dependencies
RUN pnpm install
RUN pnpm run db:generate

EXPOSE 4000

CMD ["pnpm", "run", "worker"]