FROM oven/bun:latest

WORKDIR /app/

COPY ./apps/worker/ ./apps/worker

# Copy package.json first
COPY ./packages/ ./packages
COPY package.json .
COPY bun.lock .

# Install dependencies
RUN bun install
RUN bun run db:generate

EXPOSE 4000

CMD ["bun", "run", "worker"]